defaults:
  - _self_
  - network: network
  - camera: cameras
  - controller: position
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

use_depth: False
task: drawer
retry: False

hydra:  
  output_subdir: null  
  run:  
    dir: .
  