defaults:
  - _self_
  - network: network
  - camera: iPhone
  - controller: position
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

hydra:  
  output_subdir: null  
  run:  
    dir: .
  