defaults:
  - _self_
  - network: network
  - camera: stick_iphone
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

use_depth: True

hydra:  
  output_subdir: null  
  run:  
    dir: .
  